### ISSUE TITLE
Using client via linux cluster

### ISSUE THREAD

**Issue by ajitjohnson** [dnanexus/dxda#23]
Hi, I am trying to use your client to download data. 

Here is what I have done. 

1. I downloaded the latest "dx-download-agent-linux.tar" from the release section and unzipped it. 
2. I have a Manifest file generated through your automated generation tool. 
3. Included the API key into ~/.dnanexus_config/environment.json as
```
"DX_API_TOKEN": "xxxx"
```
4. cd'd into the directory which contains both the files.
5. Used the following command to download data.

```
dx-download-agent download manifest_001.json.bz2
```
I get the following error

```
bash: dx-download-agent: command not found
```

Any idea why? Do I need to be logged into dx?

Thank you.

**Comment by orodeh** [comment]
Please try using it as follows:
```
./dx-download-agent ...
```
Also, the `DX_API_TOKEN` should be an environment variable, it shouldn't be in the `environment.json` file.
