### ISSUE TITLE
inconsistencies between argument name and outputs

### ISSUE THREAD

**Issue by aledj2** [dnanexus/dxda#54]
I'm using create_manifest.py  and filter_manifest.py .one has the output file as --output_file and the other --outfile.
Also, there doesn't seem to be and stdout for filter_manifest.py (not the end of the world, but would be good to have a success/summary statement)

**Comment by kpjensen** [comment]
Thanks! Should be standard `--output_file` across the python scripts as of https://github.com/dnanexus/dxda/pull/56.
