### ISSUE TITLE
inspect

### ISSUE THREAD

**Issue by aledj2** [dnanexus/dxda#55]
What does the inspect command do? I download the files, but before running the inspect command moved a file out and then renamed files so the contents wouldn't match.
The missing file was reported in stderr as:
panic: truncate /filepath/Undetermined_S0_R1_001.fastq.gz: no such file or directory

The file swap didn't report any error. Just want to understand what this command is doing.
Thanks

**Comment by kpjensen** [comment]
Thanks for reporting. The command is supposed to verify the md5sum of each file part, in case of file content corruption during download or write to disk. There was a bug for removal of a file, which should be fixed in https://github.com/dnanexus/dxda/releases/tag/v0.5.5.
