### ISSUE TITLE
dxda available disk space output doesn't appear correct in at least one case

### ISSUE THREAD

**Issue by geetduggal** [dnanexus/dxda#6]
@orodeh interest

![image](https://user-images.githubusercontent.com/64425/48875774-9db21e80-edc0-11e8-94fe-755926404a39.png)

I actually have 173GB free (not TB) on this test laptop. 

The test was run using a Docker image on OS X (i.e. not the executable directly on the host, but on one within the Docker container)

**Comment by orodeh** [comment]
I reread the code, and it looks correct. I need to run it, to find the actual problem.

**Comment by geetduggal** [comment]
Agreed -- I have confirmed that this issue only occurs when I run the Docker command in OS X not in linux
