### ISSUE TITLE
split_manifest.py can't parse mainfest created by create_manifest.py

### ISSUE THREAD

**Issue by ljmills** [dnanexus/dxda#67]
I have cloned the latest git repository to obtain both of these scripts and while create and filter manifest scripts work great split_manifest.py gives me the following error on both the raw and filtered manifest files I have generated. dx-download-agent-linux inspect and download works with the mainfests I have generated so it seem to be unique to split. 

Traceback (most recent call last):
  File "/home/ljmills/shared/bin/dxda/scripts/split_manifest_ljm.py", line 32, in <module>
    main()
  File "/home/ljmills/shared/bin/dxda/scripts/split_manifest_ljm.py", line 29, in main
    split_manifest(args.manifest_file, args.num_files)
  File "/home/ljmills/shared/bin/dxda/scripts/split_manifest_ljm.py", line 13, in split_manifest
    manifest = json.loads(bz2.decompress(mf.read()))
  File "/home/ljmills/shared/bin/miniconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 11: invalid start byte

**Comment by cgshuo** [comment]
Hi Lauren,
I also encountered the same problem, how did you solve it? Much apperciated for your help.

**Comment by cgshuo** [comment]
Okay, I solve the problem.  It sets the file encoding when writing the single file, but the source splitting code forgets this.
Modify the split_mainfest method in split_manifest.py as follows：
`def split_manifest(manifest_file, num_files):
    with open(manifest_file, **'rb'**) as mf:
        manifest = json.loads(bz2.decompress(mf.read()))
        for project, file_list in manifest.items():
            for i, file_subset in enumerate(chunks(file_list, num_files)):
                manifest_subset = { project: file_subset }
                outfile = "{}_{:03d}.json.bz2".format(manifest_file.rstrip(".json.bz2"), i+1)
                with open(outfile, "wb") as f:
                    f.write(bz2.compress(json.dumps(manifest_subset, indent=2, sort_keys=True)**.encode()**))
`
